### ISSUE TITLE
How can I find the mitosrun command?

### ISSUE THREAD

**Issue by codinglzc** [LLNL/Mitos#5]
Find the mitosrun command in the bin directory in the install directory.
But I don't know where the bin directory is.
Please help me! Thanks!

**Comment by alfredo-gimenez** [comment]
I should update the README, Mitos has been deprecated and all of its functionality moved to a service within another project, [Caliper](https://github.com/llnl/caliper). 

[Here](https://github.com/LLNL/Caliper/blob/master/test/cali-memtracking.cpp) and [here](https://github.com/LLNL/Caliper/blob/master/test/cali-memtracking-macros.cpp) are two examples using Caliper annotations, and [here](https://github.com/LLNL/Caliper/blob/master/examples/configs/sampled_memory_trace_pebs.conf) is an example Caliper configuration that gets a sampling of loads/stores through PEBS. Since this is a more general interface for sampling using Libpfm4, you can sample on any available events for different architectures as well.
